### ISSUE TITLE
Checklist for Version 1.0

### ISSUE THREAD

**Issue by mr-martian** [apertium/tree-sitter-apertium#4]
- [x] cg
  - [x] test against all apertium files
  - [x] add highlighting tests
  - [x] field names
- [x] lexc
  - [x] test against all apertium files
  - [x] add highlighting tests
  - [x] field names
- [x] lexd
  - [x] test against all apertium files
  - [x] ~copy lexd feature tests~
  - [x] ~handle files without final newline~
    - ~this could maybe be done by rearranging where the grammar expects `$._nl`, otherwise it'll probably have to wait for https://github.com/tree-sitter/tree-sitter/issues/160~
    - moving to separate issue and releasing without this
  - [x] field names
- [x] rtx
  - [x] test against all apertium files
  - [x] add highlighting tests
  - [x] field names
- [x] twolc
  - [x] test against all apertium files
  - [x] add syntax highlighting
  - [x] #3
  - [x] ~another NL vs EOF issue, this time with comments~
  - [x] field names
- [x] xfst
  - [x] test against all apertium files
  - [x] add syntax highlighting
  - [x] ~add HFST extensions to XEROX~
  - [x] ~field names? (or maybe more informative node names than just `expression` everywhere)~
- [x] python
  - [x] tests
  - [x] some helper functions might be nice, like for retrieving end-of-line comments in lexc

**Comment by mr-martian** [comment]
Parsers release in 98614fc
